sudo: required
services:
  - docker

before_install:
  - docker build -t mgh1990/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true mgh1990/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "frontend"
  env: "frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-164305244514"
  bucket-path: "frontend"
  on: 
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
